### ISSUE TITLE
Required to downgrade mdbook to 0.3.7

### ISSUE THREAD

**Issue by madhavajay** [Michael-F-Bryan/mdbook-epub#33]
mdbook-epub is awesome by the way! :)

I followed install instructions and added the epub entry to the master (commit bfe1ab96d717d1dda50e499b360f2e2f57e1750a) of nomicon:

```
+[output.epub]
```

Then ran:
```
 ~/Desktop/dev/nomicon   master ●  mdbook build
2020-07-03 08:32:02 [INFO] (mdbook::book): Book building has started
2020-07-03 08:32:02 [INFO] (mdbook::book): Running the epub backend
2020-07-03 08:32:02 [INFO] (mdbook::renderer): Invoking the "epub" renderer
Error: Incompatible mdbook version, expected 0.3.7 but got 0.4.0
2020-07-03 08:32:02 [ERROR] (mdbook::renderer): Renderer exited with non-zero return code.
2020-07-03 08:32:02 [ERROR] (mdbook::utils): Error: Rendering failed
2020-07-03 08:32:02 [ERROR] (mdbook::utils): 	Caused By: The "epub" renderer failed
$ mdbook --version
mdbook v0.4.0
```

Downgrading:

```
$ cargo uninstall mdbook
$ cargo install mdbook --version 0.3.7
$ mdbook build
2020-07-03 08:51:39 [INFO] (mdbook::book): Book building has started
2020-07-03 08:51:39 [INFO] (mdbook::book): Running the epub backend
2020-07-03 08:51:39 [INFO] (mdbook::renderer): Invoking the "epub" renderer
2020-07-03 08:51:39 [INFO] (mdbook::book): Running the html backend
```

Success!

**Comment by tmpfs** [comment]
Hi, I just ran into the same problem but cannot downgrade. @Michael-F-Bryan is this easily fixable? Are you interested in a PR to fix it?

FWIW, I am using mdbook@0.4 as a library so do not wish to downgrade as I am trying to keep a clear upgrade path. Upgrading mdbook as a crate from 0.37 to 0.40 was seamless so I my hunch is that upgrading here should be easy too - happy to be corrected!

**Comment by Michael-F-Bryan** [comment]
We should just need to bump the `mdbook` dependency to `0.4` and because we're using [the version number](https://github.com/Michael-F-Bryan/mdbook-epub/blob/640a81209b9de4af8da082222f31f62dc9d21af0/src/lib.rs#L39) exposed by `mdbook`, our version check should work with the latest version.

It also may be a good idea to relax [the version check](https://github.com/Michael-F-Bryan/mdbook-epub/blob/640a81209b9de4af8da082222f31f62dc9d21af0/src/lib.rs#L53-L67) so instead of requiring *exactly* `0.4.0` (or whatever the version `mdbook-epub` is compiled for) it can accept anything greater but within the same minor version. That way when `0.4.1` is released we aren't broken again.

**Comment by tmpfs** [comment]
Great, i think we can use a tilde requirement quite easily, something like:

```
VersionReq::parse(format("~{}", MDBOOK_VERSION))?;
```

**Comment by tmpfs** [comment]
What i have discovered so far is that the chapter path is now an `Option` so i just called `as_ref().unwrap()` on them and then discovered that various error handling has trait implementation errors. I am not sure why as i am not familiar with the `failure` crate.

**Comment by tmpfs** [comment]
@Michael-F-Bryan can you elucidate how I can get `failure` to play nice with `mdbook::errors::Error`?

I have a little experience writing error traits manually and using `thiserror` just not clear what the process is for `failure`.

These are the errors:

```
error[E0277]: the trait bound `mdbook::errors::Error: std::error::Error` is not satisfied
  --> src/bin/mdbook-epub.rs:42:51
   |
42 |         let md = MDBook::load(&args.root).map_err(SyncFailure::new)?;
   |                                                   ^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `mdbook::errors::Error`
   |
   = note: required by `failure::SyncFailure::<E>::new`

error[E0277]: the trait bound `mdbook::errors::Error: std::error::Error` is not satisfied
  --> src/bin/mdbook-epub.rs:42:18
   |
42 |         let md = MDBook::load(&args.root).map_err(SyncFailure::new)?;
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `mdbook::errors::Error`
   |
   = note: required by `failure::SyncFailure::<E>::new`

error[E0277]: the trait bound `failure::SyncFailure<mdbook::errors::Error>: failure::Fail` is not satisfied
  --> src/bin/mdbook-epub.rs:42:68
   |
42 |         let md = MDBook::load(&args.root).map_err(SyncFailure::new)?;
   |                                                                    ^ the trait `failure::Fail` is not implemented for `failure::SyncFailure<mdbook::errors::Error>`
   |
   = help: the following implementations were found:
             <failure::SyncFailure<E> as failure::Fail>
   = note: required because of the requirements on the impl of `std::convert::From<failure::SyncFailure<mdbook::errors::Error>>` for `failure::Error`
   = note: required by `std::convert::From::from`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `mdbook-epub`.
```

This is after upgrading to `mdbook@0.4.0` and fixing the initial `Option` issue noted above.

**Comment by Michael-F-Bryan** [comment]
> @Michael-F-Bryan can you elucidate how I can get failure to play nice with `mdbook::errors::Error`?

What error type do `mdbook` use? Nowadays I'll use normal types implementing `std::error::Error` (sometimes using `thiserror` to write the impl if I'm lazy) or `anyhow` if I just need a generic error type.

The easiest solution would be to use whatever error types `mdbook` use.

**Comment by tmpfs** [comment]
Ok, I think `anyhow` would be the right thing to do here as it's a program not a library; would that be acceptable to you if I rip out `failure` and use `anyhow` instead?

**Comment by Michael-F-Bryan** [comment]
@tmpfs, sounds good to me :+1:

**Comment by madhavajay** [comment]
I actually read this awesome article the other day on both failure and thiserror which explains how they work and their purpose / advantages:
https://nick.groenen.me/posts/rust-error-handling/

**Comment by tmpfs** [comment]
Thanks @madhavajay, good article. I actually ended up going with `thiserror` as it has better ergonomics for my taste, see #35 .

**Comment by silvioprog** [comment]
Is there any chance to use this backend with mdBook v0.4+?

Same problem: `Error: Incompatible mdbook version, expected 0.3.7 but got 0.4.6`.

Thank you!

**Comment by KUNzfw** [comment]
I have found a really simple solution.
Just clone this project and compile it by yourself after `cargo update`
```
cargo update
cargo install --path .
```
Done.

**Comment by netthier** [comment]
That indicates that the fix is in master, but no version containing that fix has been published to crates.io yet.
Seems a version bump is required @Michael-F-Bryan

**Comment by Michael-F-Bryan** [comment]
@blandger or @glottologist, would you be able to look into this? You should have permission to upload new versions to crates.io.

**Comment by blandger** [comment]
I'll try to look that and build, but I'm not sure I know how to do release build and put it into crates.
Should I do something special for release?

**Comment by Michael-F-Bryan** [comment]
[This page from the Cargo Book](https://doc.rust-lang.org/cargo/reference/publishing.html) should explain the process and how to authenticate with crates.io, but the bare minimum you need to do is change the version number in `Cargo.toml` and run `cargo publish`.

I normally use [the `cargo release patch --sign` command](https://crates.io/crates/cargo-release) because it automates the process of bumping version numbers, making a "released v1.2.3" commit and tagging it, publishing to crates.io, and bumping to a `-dev` version.

**Comment by glottologist** [comment]
@blandger @Michael-F-Bryan I can do this if no-one else has picked it up yet?

**Comment by akiradeveloper** [comment]
Same issue here. 

> Error: Incompatible mdbook version, expected 0.3.7 but got 0.4.5

**Comment by blandger** [comment]
@glottologist @akiradeveloper update changes were merged into master. I will try to tag and publish new version into crates soon.

If you hurry to run that asap...
Usually I'm using my own locally patched mdbook-epub version from:
https://github.com/blandger/mdbook-epub/blob/add_links_preprocessing/Cargo.toml
(patched epub-builder to have correct epub files on Eink-readers, patched mdBook to correctly process included /*.rs file in text as code pieces, tested mostly for rust-book)

I use linux command like that:
param to see the log *RUST_LOG=debug* is optional, but it can be used in case error for diagnosis.
/path_to_md_book_sources/ is folder with 'book.toml' in root

`RUST_LOG=debug /mdbook-epub/target/debug/mdbook-epub /path_to_md_book_sources/`

**Comment by blandger** [comment]
@Michael-F-Bryan 
Looks like not enough permissions (on crates) ?

Latest step on `cargo publish` gives error:
```
error: failed to publish to registry at https://crates.io
Caused by:
  the remote server responded with an error: this crate exists but you don't seem to be an owner. If you believe this is a mistake, perhaps you need to accept an invitation to be an owner before publishing.
```

**Comment by Michael-F-Bryan** [comment]
Do you see any pending invites on crates.io?

![2022-01-06_16-16-40-12](https://user-images.githubusercontent.com/17380079/148354429-58b9eb13-a346-48af-8a40-3b18944cfcb9.png)

**Comment by blandger** [comment]
Yes I see, accepted and tried one more time.
I'll solve next issue 

```
error: failed to publish to registry at https://crates.io
Caused by:
  the remote server responded with an error: wildcard (`*`) dependency constraints are not allowed on crates.io. See https://doc.rust-lang.org/cargo/faq.html#can-libraries-use--as-a-version-for-their-dependencies for more information
```

**Comment by blandger** [comment]
Done.
New version is published.
Does it look correct or I missed something?

https://crates.io/crates/mdbook-epub/versions

**Comment by akiradeveloper** [comment]
Thanks. I updated to the new version

```
$ cargo install mdbook-epub --version 0.4.14-alpha.0
```

Now the version mismatch seems to be resolved but how can I solve this new error?

```
$ mdbook build
2022-01-07 11:31:02 [INFO] (mdbook::book): Book building has started
2022-01-07 11:31:02 [INFO] (mdbook::book): Running the epub backend
2022-01-07 11:31:02 [INFO] (mdbook::renderer): Invoking the "epub" renderer
thread 'main' panicked at 'Failed finding/fetch resource taken from content? Look up content for possible error...: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })', /Users/akira.hayakawa/.cargo/registry/src/github.com-1ecc6299db9ec823/mdbook-epub-0.4.14-alpha.0/src/generator.rs:170:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-01-07 11:31:03 [ERROR] (mdbook::renderer): Renderer exited with non-zero return code.
2022-01-07 11:31:03 [ERROR] (mdbook::utils): Error: Rendering failed
2022-01-07 11:31:03 [ERROR] (mdbook::utils): 	Caused By: The "epub" renderer failed
```

It should related to this part of the code.

```rust
    fn additional_assets(&mut self) -> Result<(), Error> {
        debug!("Embedding additional assets");

        let error = String::from("Failed finding/fetch resource taken from content? Look up content for possible error...");
        // resources::find can emit very unclear error based on internal MD content,
        // so let's give a tip to user in error message
        let assets = resources::find(self.ctx).expect(&error);
```

 I don't know why it is trying to find a additional assets  while I am not setting anything about it in config

```
[output.epub]
```

My thought on this is that the intention is early return if the assets are not found and it is a simple degrade from this patch　https://github.com/Michael-F-Bryan/mdbook-epub/commit/78d9927e79d36603aef25f2867ea74106fcaac4d

**Comment by blandger** [comment]
You have some kind of embedded resource in the source MD file, like picture of similar...
You have to specify them explicitly in book.toml file like below

```
[output.epub]
cover-image = "img/book_cover.jpg"
additional-resources = ["img/ferris/does_not_compile.svg","img/ferris/not_desired_behavior.svg","img/trpl15-02.svg","img/trpl15-03.svg","img/trpl15-04.svg"]
```

so they will be processed correctly and embedded into epub. Much better to use **RUST_LOG=debug** because it gives better error reporting in log. That's up to you,

**Comment by akiradeveloper** [comment]
@blandger 

Not working yet.

Surprisingly, only adding `output.epub` to the dummy book works although Chapter1.md includes a path to an image. Why not needing additional-resources in this case?

```diff
$ git di
diff --git a/tests/dummy/book.toml b/tests/dummy/book.toml
index 02d506ee..d8242859 100644
--- a/tests/dummy/book.toml
+++ b/tests/dummy/book.toml
@@ -3,3 +3,5 @@ title = "DummyBook"
 authors = []
 multilingual = false
 src = "src"
+
+[output.epub]
```

Also, the example in README seems to indicate that the additional-resources should be some relative path starting from dot, which is not consistent with your advice above. Which is correct?

```
[output.epub]
additional-css = ["./path/to/main.css"]
use-default-css = false
cover-image = "ebook-cover.png"
additional-resources = ["./assets/Open-Sans-Regular.ttf"]
```

My book structure is like this which is normally renderable when output.epub lines are removed.

```
book.toml

// content of book.toml
src = "book-src"
[output.epub]
additional-resources = ["images/x.png"]

book-src
book-src/SUMMARY.md
book-src/x.md // includes images/y.png
book-src/images/y.png

**Comment by akiradeveloper** [comment]
Oh it is working!

I found one of my documents includes a path to web image. The error message is still not helpful.

Also, I finally realize we don't need to add all the images as long as they are found under src directory. My book now works with output.epub line only.

**Comment by blandger** [comment]
@akiradeveloper As far as I remember internal logic makes two predictions about possible resource placement, like _try to find relatively to /src or /root_ (if I'm not mistaken) and can find them 'silently'. If those two are failed the _additional-resources_ can help to work around alternative placement. Otherwise it fails with error as you showed after first attempt.

> ...my documents includes a path to web image

Yes, that doesn't work. Some notes about external resources:
http://idpf.org/epub/30/spec/epub30-publications.html#sec-resource-locations

**Comment by blandger** [comment]
Closed.

**Comment by huangjj27** [comment]
Sad that Similar issue encountered with the `0.4.34` version from crates.io (with mirror rsproxy)
```
> cargo install mdbook-epub -f   
    Updating `rsproxy` index
remote: Counting objects: 250933, done.
remote: Compressing objects: 100% (79780/79780), done.
remote: Total 250933 (delta 188123), reused 230121 (delta 167480) eceiving objects: 100% (250933/250933), 122.05 MiB | 11.22 MiB/s
Receiving objects: 100% (250933/250933), 123.95 MiB | 8.33 MiB/s, done.
Resolving deltas: 100% (188123/188123), completed with 7706 local objects.
From https://rsproxy.cn/crates.io-index
 + 002b5f756b3...ce403eba4c7            -> origin/HEAD  (forced update)
  Downloaded mdbook-epub v0.4.34 (registry `rsproxy`)
  Downloaded 1 crate (60.6 KB) in 17.39s
  Installing mdbook-epub v0.4.34
  Downloaded thiserror-impl v1.0.50 (registry `rsproxy`)
  Downloaded rustls-webpki v0.101.7 (registry `rsproxy`)
  Downloaded thiserror v1.0.50 (registry `rsproxy`)
  Downloaded syn v2.0.39 (registry `rsproxy`)
  Downloaded sct v0.7.1 (registry `rsproxy`)
  Downloaded cc v1.0.83 (registry `rsproxy`)
  Downloaded byteorder v1.5.0 (registry `rsproxy`)
  Downloaded serde_json v1.0.108 (registry `rsproxy`)
  Downloaded pest_derive v2.7.5 (registry `rsproxy`)
  Downloaded env_logger v0.10.1 (registry `rsproxy`)
  Downloaded pest_generator v2.7.5 (registry `rsproxy`)
  Downloaded proc-macro2 v1.0.70 (registry `rsproxy`)
  Downloaded tempfile v3.8.1 (registry `rsproxy`)
  Downloaded regex-automata v0.4.3 (registry `rsproxy`)
  Downloaded unicode-width v0.1.11 (registry `rsproxy`)
  Downloaded getrandom v0.2.11 (registry `rsproxy`)
  Downloaded serde v1.0.193 (registry `rsproxy`)
  Downloaded form_urlencoded v1.2.1 (registry `rsproxy`)
  Downloaded pest_meta v2.7.5 (registry `rsproxy`)
  Downloaded regex v1.10.2 (registry `rsproxy`)
  Downloaded clap_lex v0.6.0 (registry `rsproxy`)
  Downloaded webpki-roots v0.25.3 (registry `rsproxy`)
  Downloaded utf8-width v0.1.7 (registry `rsproxy`)
  Downloaded rustc-demangle v0.1.23 (registry `rsproxy`)
  Downloaded const_format v0.2.32 (registry `rsproxy`)
  Downloaded handlebars v4.5.0 (registry `rsproxy`)
  Downloaded base64 v0.21.5 (registry `rsproxy`)
  Downloaded clap_complete v4.4.4 (registry `rsproxy`)
  Downloaded clap v4.4.10 (registry `rsproxy`)
  Downloaded const_format_proc_macros v0.2.32 (registry `rsproxy`)
  Downloaded untrusted v0.9.0 (registry `rsproxy`)
  Downloaded termcolor v1.4.0 (registry `rsproxy`)
  Downloaded rustls v0.21.9 (registry `rsproxy`)
  Downloaded ring v0.17.5 (registry `rsproxy`)
  Downloaded idna v0.5.0 (registry `rsproxy`)
  Downloaded url v2.5.0 (registry `rsproxy`)
  Downloaded libc v0.2.150 (registry `rsproxy`)
  Downloaded clap_builder v4.4.9 (registry `rsproxy`)
  Downloaded spin v0.9.8 (registry `rsproxy`)
  Downloaded flate2 v1.0.28 (registry `rsproxy`)
  Downloaded html_parser v0.7.0 (registry `rsproxy`)
  Downloaded percent-encoding v2.3.1 (registry `rsproxy`)
  Downloaded ureq v2.9.1 (registry `rsproxy`)
  Downloaded semver v1.0.20 (registry `rsproxy`)
  Downloaded miniz_oxide v0.7.1 (registry `rsproxy`)
  Downloaded serde_derive v1.0.193 (registry `rsproxy`)
  Downloaded pest v2.7.5 (registry `rsproxy`)
  Downloaded cpufeatures v0.2.11 (registry `rsproxy`)
  Downloaded backtrace v0.3.69 (registry `rsproxy`)
  Downloaded regex-syntax v0.8.2 (registry `rsproxy`)
  Downloaded 50 crates (9.3 MB) in 19.73s (largest was `ring` at 4.1 MB)
   Compiling proc-macro2 v1.0.70
   Compiling unicode-ident v1.0.12
   Compiling version_check v0.9.4
   Compiling windows_x86_64_msvc v0.48.5
   Compiling winapi v0.3.9
   Compiling cfg-if v1.0.0
   Compiling thiserror v1.0.50
   Compiling cc v1.0.83
   Compiling memchr v2.6.4
   Compiling serde v1.0.193
   Compiling log v0.4.20
   Compiling ucd-trie v0.1.6
   Compiling unicode-width v0.1.11
   Compiling once_cell v1.18.0
   Compiling crc32fast v1.3.2
   Compiling getrandom v0.2.11                                                                                                                        
   Compiling autocfg v1.1.0                                                                                                                           
   Compiling regex-syntax v0.8.2                                                                                                                      
   Compiling utf8parse v0.2.1                                                                                                                         
   Compiling anstyle v1.0.4
   Compiling anstyle-parse v0.2.2                                                                                                                     
   Compiling tinyvec_macros v0.1.1                                                                                                                    
   Compiling unicase v2.7.0                                                                                                                           
   Compiling proc-macro-error-attr v1.0.4                                                                                                             
   Compiling windows-targets v0.48.5                                                                                                                  
   Compiling windows-sys v0.48.0                                                                                                                      
   Compiling aho-corasick v1.1.2
   Compiling colorchoice v1.0.0
   Compiling serde_json v1.0.108                                                                                                                      
   Compiling num-traits v0.2.17                                                                                                                       
   Compiling spin v0.9.8
   Compiling libc v0.2.150                                                                                                                            
   Compiling syn v1.0.109                                                                                                                             
   Compiling untrusted v0.9.0                                                                                                                         
   Compiling tinyvec v1.6.0
   Compiling proc-macro-error v1.0.4                                                                                                                  
   Compiling clap_lex v0.6.0                                                                                                                          
   Compiling quote v1.0.33                                                                                                                            
   Compiling strsim v0.10.0                                                                                                                           
   Compiling humantime v2.1.0
   Compiling bitflags v1.3.2
   Compiling syn v2.0.39
   Compiling ryu v1.0.15                                                                                                                              
   Compiling itoa v1.0.9
   Compiling error-chain v0.12.4                                                                                                                      
   Compiling anstyle-query v1.0.0                                                                                                                     
   Compiling anstyle-wincon v3.0.1                                                                                                                    
   Compiling terminal_size v0.3.0
   Compiling unicode-normalization v0.1.22                                                                                                            
   Compiling ring v0.17.5
   Compiling anstream v0.6.4
   Compiling backtrace v0.3.69                                                                                                                        
   Compiling unicode-segmentation v1.10.1
   Compiling adler v1.0.2
   Compiling pulldown-cmark v0.9.3
   Compiling unicode-bidi v0.3.13                                                                                                                     
   Compiling anyhow v1.0.75                                                                                                                           
   Compiling clap_builder v4.4.9                                                                                                                      
   Compiling regex-automata v0.4.3                                                                                                                    
   Compiling rustc-demangle v0.1.23
   Compiling doc-comment v0.3.3
   Compiling percent-encoding v2.3.1                                                                                                                  
   Compiling rustls v0.21.9                                                                                                                           
   Compiling form_urlencoded v1.2.1                                                                                                                   
   Compiling idna v0.5.0
   Compiling heck v0.3.3                                                                                                                              
   Compiling chrono v0.4.31                                                                                                                           
   Compiling miniz_oxide v0.7.1                                                                                                                       
   Compiling mime_guess v2.0.4                                                                                                                        
   Compiling is-terminal v0.4.9                                                                                                                       
   Compiling normpath v1.1.1                                                                                                                          
   Compiling winapi-util v0.1.6                                                                                                                       
   Compiling atty v0.2.14                                                                                                                             
   Compiling time v0.1.45                                                                                                                             
   Compiling termcolor v1.4.0                                                                                                                         
   Compiling rand v0.4.6
   Compiling remove_dir_all v0.5.3                                                                                                                    
   Compiling log v0.3.9                                                                                                                               
   Compiling thiserror-impl v1.0.50                                                                                                                   
   Compiling serde_derive v1.0.193                                                                                                                    
   Compiling clap v4.4.10
   Compiling getopts v0.2.21                                                                                                                          
   Compiling regex v1.10.2                                                                                                                            
   Compiling textwrap v0.11.0                                                                                                                         
   Compiling fastrand v2.0.1                                                                                                                          
   Compiling strsim v0.8.0                                                                                                                            
   Compiling unicode-xid v0.2.4                                                                                                                       
   Compiling vec_map v0.8.2                                                                                                                           
   Compiling byteorder v1.5.0                                                                                                                         
   Compiling utf8-width v0.1.7                                                                                                                        
   Compiling lazy_static v1.4.0
   Compiling semver v1.0.20                                                                                                                           
   Compiling html-escape v0.2.13
   Compiling clap v2.34.0                                                                                                                             
   Compiling pest v2.7.5                                                                                                                              
   Compiling zip v0.5.13                                                                                                                              
   Compiling const_format_proc_macros v0.2.32                                                                                                         
   Compiling tempfile v3.8.1                                                                                                                          
   Compiling structopt-derive v0.4.18                                                                                                                 
   Compiling env_logger v0.10.1
   Compiling env_logger v0.8.4                                                                                                                        
   Compiling sct v0.7.1                                                                                                                               
   Compiling rustls-webpki v0.101.7                                                                                                                   
   Compiling pest_meta v2.7.5                                                                                                                         
   Compiling tempdir v0.3.7                                                                                                                           
   Compiling clap_complete v4.4.4                                                                                                                     
   Compiling opener v0.6.1                                                                                                                            
   Compiling flate2 v1.0.28                                                                                                                           
   Compiling pest_generator v2.7.5                                                                                                                    
   Compiling url v2.5.0                                                                                                                               
   Compiling pest_derive v2.7.5                                                                                                                       
   Compiling uuid v0.8.2                                                                                                                              
   Compiling mime v0.3.17                                                                                                                             
   Compiling base64 v0.21.5                                                                                                                           
   Compiling topological-sort v0.2.2                                                                                                                  
   Compiling webpki-roots v0.25.3                                                                                                                     
   Compiling shlex v1.2.0                                                                                                                             
   Compiling structopt v0.3.26                                                                                                                        
   Compiling ureq v2.9.1                                                                                                                              
   Compiling const_format v0.2.32
   Compiling toml v0.5.11                                                                                                                             
   Compiling mustache v0.9.0
   Compiling epub-builder v0.5.0                                                                                                                      
   Compiling handlebars v4.5.0
   Compiling html_parser v0.7.0                                                                                                                       
   Compiling mdbook v0.4.35
   Compiling mdbook-epub v0.4.34                                                                                                                      
    Finished release [optimized] target(s) in 3m 24s
   Replacing D:\Program Files\.cargo\bin\mdbook-epub.exe
    Replaced package `mdbook-epub v0.4.25 (registry `rsproxy`)` with `mdbook-epub v0.4.34` (executable `mdbook-epub.exe`)
> mdbook build
2023-11-28 22:48:44 [INFO] (mdbook::book): Book building has started
2023-11-28 22:48:44 [INFO] (mdbook::book): Running the epub backend
2023-11-28 22:48:44 [INFO] (mdbook::renderer): Invoking the "epub" renderer
Running mdbook-epub as plugin...
[2023-11-28T14:48:44Z ERROR mdbook_epub] Incompatible mdbook version got 0.4.35 expected 0.4.26
2023-11-28 22:48:44 [ERROR] (mdbook::renderer): Renderer exited with non-zero return code.
2023-11-28 22:48:44 [ERROR] (mdbook::utils): Error: Rendering failed
2023-11-28 22:48:44 [ERROR] (mdbook::utils):    Caused By: The "epub" renderer failed
> rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.72.0 (5680fa18f 2023-08-23)`
```
